name: CI / Build & Push image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: shuratsyganok/linux-quiz-bot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install deps & run flake8/pytest
      run: |
        pip install -r requirements.txt flake8 pytest
        flake8 bot
        pytest -q

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract tag (yyyymmdd-hhmm)
      id: vars
      run: echo "TAG=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT

    - name: Build & push image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Upload tag as artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: image-tag
        path: |
          tag.txt
      run: echo "${{ steps.vars.outputs.TAG }}" > tag.txt
