services:
  bot:
    image: docker.io/${DOCKERHUB_USERNAME}/linux-quiz-bot:${IMAGE_TAG}
    container_name: linux-quiz-bot-dev
    restart: unless-stopped
    env_file: .env.dev
    ports:
      - "8081:8080"