services:
  bot:
    image: docker.io/${DOCKERHUB_USERNAME}/linux-quiz-bot:${IMAGE_TAG}
    container_name: linux-quiz-bot-prod
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "8080:8080"

