version: "3.8"

services:
  bot:
    build: .
    command: python -m bot
    working_dir: /app
    volumes:
      - .:/app                 # 💡 целиком проект (проще)
    env_file: .env.dev         # имя прямо, без переменных
    restart: unless-stopped
