services:
  bot:
    container_name: linux-quiz-bot-dev
    build: .
    command: python -m bot
    working_dir: /app
    volumes:
      - .:/app
    env_file: .env.dev
    environment:
      - BOT_TOKEN_DEV
      - LOG_LEVEL
      - ENV
      - PYTHONUNBUFFERED=1
    restart: unless-stopped