name: Local deploy
on:
  workflow_run:
    workflows: [ "CI" ]
    branches:  [ main ]
    types:     [ completed ]

jobs:
  rollout:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted              # <-- ваш раннер

    steps:
      - uses: actions/checkout@v4

      - name: Pull & restart container
        run: |
          docker pull docker.io/${{ secrets.DOCKERHUB_USER }}/linux-quiz-bot:latest
          docker compose up -d --force-recreate
